version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    #command: bash -c "alembic upgrade head  && uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
        - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - ./rabbitmq/logs:/var/log/rabbitmq/log
    env_file:
        - ./backend/.env
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
        - 5672:5672
        - 15672:15672

    
    

volumes:
    postgres_data: